def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
def floor_(a,b):
    return a//b
def power_(a,b):
    return a**b
def modulo(a,b):
    return a%b
def cap(a,b):
    return a^b
